# Remote theme, use the latest version
remote_theme: wet-boew/gcweb-jekyll

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- Gemfile
- Gemfile.lock
- gcweb-jekyll.gemspec

# 7. Site settings
assets: "https://wet-boew.github.io/themes-dist"
description:
  en: "GST/HST for small Businesses" # English site description and default description
  fr: "TPS/TVH pour les pour les petites entreprises" # French site description and default description

# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
      type: pages
    values:
      layout: default
      lang: "en"
      altLangPage: "#"
      share: true
      sitemenu: true
      sitesearch: true
      feedback: true
      feedbackPath: "https://www.canada.ca/etc/designs/canada/wet-boew/assets/feedback/page-feedback-en.html"
      css: "https://use.fontawesome.com/releases/v5.15.4/css/all.css"
      script: "https://www.canada.ca/etc/designs/canada/wet-boew/js/ep-pp.min.js"
      contextualFooter: true
      contextualFooterTitle: "Canada Revenue Agency (CRA)"
      footerIncludeVersion: "v1"
      noFooterContextual: false
  -
    scope:
      path: "en/"
    values:
      lang: "en"
  -
    scope:
      path: "fr/"
    values:
      lang: "fr"
